### PR TITLE
Fixed error in playerutils.js file [Delivers JW7-1246]

### PR DESCRIPTION
**Pull request by pajong**
@donato Can you please check this? Thank you

### CODE REVIEW

**Comment by dannyfinks** [comment]
@pajong @donato will this resolve https://jwplayer.atlassian.net/browse/JW7-1252 ?

**Comment by donato** [comment]
JW7-1246 #Merged

**Comment by donato** [comment]
JW7-1246 #Merge

**Comment by donato** [comment]
JW7-1246 #Merges ???

**Pull request merged**
