### PR TITLE
[JW8-11885] Fix playReason not updating after a seek event

### PR DESCRIPTION
**Pull request by Dawolee**
### This PR will...
Assure that after a seek event, the appropriate playReason (external vs interaction) is assigned to the playReason attribute.
### Why is this Pull Request needed?
More consistency with player event reporting
#### Addresses Issue(s):

JW8-11885

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1889/) MULTI Build for commit ac06e2d5ae0988b3ee53f95d9c9b30ef82835bde is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9310/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9310/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6256/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6256/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28368/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28368/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23823/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23823/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5989/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28368/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28368/archive/test/view/) Views

**Comment by zetagame** [comment]
lgtm. @robwalch are there any other player states that would result in playing after seeking?

**Review by zetagame — APPROVED** [review]

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1916/) MULTI Build for commit cb1a3b29d0dc1ecf0a23ef31172b24ad4386139f is unstable (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9342/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9342/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6283/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6283/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28423/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28423/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23870/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23870/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/6037/allure/) FAILURE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28423/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28423/archive/test/view/) Views

**Comment by pajong** [comment]
test this please

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1922/) MULTI Build for commit cb1a3b29d0dc1ecf0a23ef31172b24ad4386139f is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9349/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9349/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6290/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6290/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28460/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28460/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23903/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23903/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/6066/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28460/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28460/archive/test/view/) Views

**Pull request merged**
