### PR TITLE
[JW8-11903] Fix lingering UI.js issues from click changes

### PR DESCRIPTION
**Pull request by zetagame**
### This PR will...
- Ensure focus listeners are added first. 
- Prevent enter from being handled as click (modern browsers dispatch a click event when pressing enter on a menu item).

### Why is this Pull Request needed?
As a result of the previous change, focus/blur listener were not being added. 

To prevent duplication of focus listeners in UI, we first check if `SELECT_GROUP` or `INIT_GROUP` exists in ui handlers, as both of these handler groups require focus listeners. We're currently appending these listeners was set to run _after_ these groups were created, not before, thus guaranteeing a falsy result every time. By moving `initFocusListeners()` ahead of `initStartEventsListeners()`, we ensure an accurate result every time, and continue to avoid adding duplicate focus listeners.

### Are there any points in the code the reviewer needs to double check?
[There might be a better way to go about this](https://github.com/jwplayer/jwplayer/pull/3876)

#### Addresses Issue(s):

JW8-1903

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1859/) MULTI Build for commit 35a324e5c9d426bbd49f5dbe7195a89afb254e00 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9275/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9275/consoleFull) jwplayer build FAILURE
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/consoleFull) jwplayer unit tests NOT_STARTED
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1860/) MULTI Build for commit 36896e85c533464a7b69b6ed1f8513fbd850d909 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/consoleFull) jwplayer build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6227/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6227/consoleFull) jwplayer unit tests FAILURE
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1861/) MULTI Build for commit 13e373fe825e41cd7f0f85026c0919c9c6b0c9af is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9277/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9277/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6228/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6228/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28282/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28282/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23746/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23746/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5919/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28282/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28282/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1863/) MULTI Build for commit f33a59583f845bab63cd6062cc1a2bbdb6c843b0 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9279/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9279/consoleFull) jwplayer build FAILURE
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/consoleFull) jwplayer unit tests NOT_STARTED
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1864/) MULTI Build for commit 0a9bdc5ac89f382501235d3c988541c82646be81 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/consoleFull) jwplayer build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6231/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6231/consoleFull) jwplayer unit tests FAILURE
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1865/) MULTI Build for commit 5b2a248d8366fd8ca31342d8a19e0e361bae64d9 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/consoleFull) jwplayer build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6232/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6232/consoleFull) jwplayer unit tests FAILURE
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by zetagame** [comment]
test this please

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1866/) MULTI Build for commit 5b2a248d8366fd8ca31342d8a19e0e361bae64d9 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9282/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9282/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6233/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6233/consoleFull) jwplayer unit tests FAILURE
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1867/) MULTI Build for commit 87f8beb191f17ab92b0cdb0047f05f002d963864 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9283/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9283/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6234/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6234/consoleFull) jwplayer unit tests FAILURE
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1868/) MULTI Build for commit 616e17f264f3e658e2ce84b9f0fe46726227e11b is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9284/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9284/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6235/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6235/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28284/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28284/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23748/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23748/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5920/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28284/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28284/archive/test/view/) Views

**Review by pajong — APPROVED** [review]

**Review by mamaddox — APPROVED** [review]

**Pull request merged**
