### PR TITLE
Deselect previous audio track when using setCurrentAudioTrack

### LINKED ISSUE #3685: SetCurrentAudioTrack doesn't deselect the previous in the UI
### Expected Behavior

When programatically changing current audio track through setCurrentAudioTrack(index) the current audio track should be the only "selected" audio track in the UI.

### Actual Behavior

After doing setCurrentAudioTrack(index) the previous audio track is still selected in the UI, which makes it unclickable. One has to select another audio track to clear it. The audio is fine.
image

### Steps to reproduce

1. Have a video with multiple audio tracks, like this demo: https://www.jwplayer.com/developers/web-player-demos/hlsv4-audio-tracks/
2. Run ```jwplayer().setCurrentAudioTrack(1)```
3. Look at the audio tracks

### Environment

- Google Chrome | Version 81.0.4044.138 (Official Build) (64-bit)
- 8.14.0 | https://cdn.jwplayer.com/libraries/wr6i4gal.js

### PR DESCRIPTION
**Pull request by LuaxY**
### This PR will...

Fix #3685

### Why is this Pull Request needed?

To be able to properly use both audio track menu and JS API `setCurrentAudioTrack`.

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by jnatalzia** [comment]
Closing as underlying issue was solved in 8.15.0

**Comment by LuaxY** [comment]
Hi @jnatalzia , the bug is still present on 8.15.0, the MR was originally created for this version

**Comment by jnatalzia** [comment]
Hm interesting the opener of the linked issue said that their issue was fixed by 8.15.0. Will reopen and test to ensure this is still a problem

**Comment by andreasgan** [comment]
The issue is back in 8.15.2. I don't understand how it got fixed without merging this in the first place? But I'm running the commercial version from jwplatform.com; that version is maybe not consistent with the master branch of this repo?

**Comment by robwalch** [comment]
Hi @LuaxY (cc @andreasgan),

Are you still seeing this issue in 8.17.3?

I marked the linked issue as fixed https://github.com/jwplayer/jwplayer/issues/3685#issuecomment-674094045 and just want to confirm that this PR can be closed.

Thanks!

**Pull request closed without merging**
