### PR TITLE
[JW8-11406][JW8-11459] Only load Tizen styles with tizen controls

### PR DESCRIPTION
**Pull request by mamaddox**
### This PR will...
- Remove `tizen.less` from `controls.less` to only load tizen styles with `tizen-controls`
- Separate tizen styles into different files for clarity
- Update the following files to add style flexibility across resolutions
  - `tizen-ads.less`
  - `tizen-controlbar.less`
  - `tizen-nextup.less`
  - `tizen-pause-display.less`

### Why is this Pull Request needed?
Tizen App
#### Addresses Issue(s):

JW8-11406 / JW8-11459

Relates to: https://github.com/jwplayer/jwplayer/pull/3626

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1590/) MULTI Build for commit e1683435deca6b8a057644df92aff29580a7f6ba is unstable (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8908/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8908/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5957/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5957/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26961/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26961/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/22615/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/22615/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/4888/allure/) FAILURE
[:eggplant:](http://player-pr-test-jenkins.longtailvideo.com/builds/26961/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/26961/archive/test/view/) Views

**Comment by mamaddox** [comment]
test this please

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1593/) MULTI Build for commit e1683435deca6b8a057644df92aff29580a7f6ba is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8911/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8911/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5960/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5960/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26966/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26966/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/22620/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/22620/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/4896/allure/) UNSTABLE
[:eggplant:](http://player-pr-test-jenkins.longtailvideo.com/builds/26966/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/26966/archive/test/view/) Views

**Review by zetagame — APPROVED** [review]

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1594/) MULTI Build for commit dc56118bc896143d8ea7b4ae847df9f5a3f76221 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8912/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8912/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5961/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5961/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/22630/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/22630/consoleFull) jwplayer-commercial unit tests FAILURE
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:eggplant:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by robwalch** [comment]
@mamaddox rebase to fix failing unit tests.

**Review by zetagame — APPROVED** [review]

**Review by robwalch — COMMENTED** [review]
It would be good to mention #3626 in the description.

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1599/) MULTI Build for commit 234cd3f987d2f9d745c76820c5dd0cafef3c4b0c is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8917/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8917/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5966/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5966/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26985/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26985/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/22637/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/22637/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/4909/allure/) UNSTABLE
[:eggplant:](http://player-pr-test-jenkins.longtailvideo.com/builds/26985/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/26985/archive/test/view/) Views

**Pull request merged**
