### PR TITLE
[JW8-11660] Switch from yarn to npm

### PR DESCRIPTION
**Pull request by mamaddox**
### This PR will...
- Update yarn references to npm
- Replace yarn.lock file with package-lock.json
### Why is this Pull Request needed?
Yarn to NPM Migration

#### Addresses Issue(s):

JW8-11660

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1775/) MULTI Build for commit 83d2d7a4e0c5a4608d17bd8f8b312f09883e2817 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9161/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9161/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6142/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6142/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/27991/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/27991/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23495/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23495/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5719/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/27991/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/27991/archive/test/view/) Views

**Review by robwalch — APPROVED** [review]

**Review by zetagame — APPROVED** [review]

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1831/) MULTI Build for commit 2d94ccd6105643d4257c1343ba8b20c2ea465eb1 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9234/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9234/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6198/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6198/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23625/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23625/consoleFull) jwplayer-commercial unit tests FAILURE
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by mamaddox** [comment]
test this please

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1832/) MULTI Build for commit 2d94ccd6105643d4257c1343ba8b20c2ea465eb1 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9235/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9235/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6199/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6199/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28147/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28147/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23632/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23632/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5831/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28147/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28147/archive/test/view/) Views

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1834/) MULTI Build for commit 30d60df83ed46fd70c86915403dd0acccdf54731 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9237/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9237/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6201/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6201/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28156/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28156/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23639/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23639/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5839/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28156/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28156/archive/test/view/) Views

**Pull request merged**
