### PR TITLE
[JW8-1290] Display autostart unmute button only on touch.

### PR DESCRIPTION
**Pull request by vseventer**
### This PR will...
Hide the autostart unmute button on desktop and only show if the player has `jw-flag-touch`.

### Why is this Pull Request needed?
The autostart unmute button cannot be interacted with on desktop, as hovering it will display the full controlbar instead.

### Are there any points in the code the reviewer needs to double check?
Alternatively, we can move the `OS.mobile` check to inside `setupUnmuteAutoplayButton` in `controls.js` to not render the button in the first place. But, looking at how we general do things, we simply hide the button using CSS.

#### Addresses Issue(s):
JW8-1290

### CODE REVIEW

**Comment by johnBartos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  🛠 There are modified src files, but no test changes. Add tests if you're able to.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  🔎 Assign some reviewers or assignees.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  🗿 Set a milestone. It should be the ticket's fix version in JIRA.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by egreaves** [comment]
@vseventer I actually prefer the idea of using JS to setup the mute button only on mobile devices. The CSS solution would be better if it was likely that we'd need to toggle between mobile/desktop views, but that's not the case.

**Comment by vseventer** [comment]
@egreaves Although I agree, I want to make sure this is what we want to do, since nowhere else in the code we seem to conditionally render elements based on OS, it's all done through CSS. /cc @robwalch @DanFerrer

**Comment by robwalch** [comment]
I'm fine with this. It's not UI that pubs should customize. We are creating this element conditionally, so there is no reason to add it if it will never be shown. Pubs can style the controlbar.

**Pull request merged**
