### PR TITLE
6.12 rc1

### PR DESCRIPTION
**Pull request by robwalch**

### CODE REVIEW

**Comment by fdambrosio** [comment]
I've checked a very big problem with 6.11 and long duration hls stream. We can't play after 3 hours and 30 minutes files, because the player stop playing and go to next file in playlist or go back to the start. 
We've checked this problem with mp4, m4a, mp3 and f4v file format, so the problem there's for all hls stream with flash player. 
Playing with other player/iOS all stream good until the end. 
Trying with previous version like 6.10 we haven't problem and all stream play fine until the end. So the problem is new with 6.11. 
(p.s. and there is Firefox/Win full screen freeze bug)

**Comment by emaxsaun** [comment]
@fdambrosio - Please contact support directly concerning these issues. The email is support [at] jwplayer [dot] com. The support team will be able to help you out. Please make sure to provide links to your issues.

**Comment by robwalch** [comment]
@fdambrosio please send us the HLS playlist (.m3u8 file) you are experiencing the problem with.

**Comment by fdambrosio** [comment]
For example: 
http://video-4.radioradicale.it:1935/store-58/_definst_/mp4:roma/2014/01//FL761053.f4v/playlist.m3u8
http://video-4.radioradicale.it:1935/store-58/_definst_/mp3:roma/2014/01//MP760875.mp3/playlist.m3u8
http://audio-aac.radioradicale.it:1935/aac-1/_definst_/2015/01/18/MP760875.m4a/playlist.m3u8

All works fine with 6.10

**Comment by emaxsaun** [comment]
@fdambrosio Thanks

**Comment by fdambrosio** [comment]
new hls stream on new wowza 3.64 server, same problem: http://video-3.radioradicale.it:1935/store-70/_definst_/mp3:MP370025.mp3/playlist.m3u8

**Comment by emaxsaun** [comment]
Thank you @fdambrosio, we will look into it.

**Pull request merged**
