### PR TITLE
Stopped UCBrowser as being detected as Chrome

### PR DESCRIPTION
**Pull request by waxidiotic**
JW8-1256

### This PR will...

Exclude browsers with user-agent strings that include `UCBrowser` from being interpreted as Chrome in `getEnvironment()`.

### Why is this Pull Request needed?

This will allow publishers to work around features that are not supported in UC Browser but are in Chrome. It also should improve the chance that returning `true` for Chrome would be correct.

### Are there any points in the code the reviewer needs to double check?

n/a

### Are there any Pull Requests open in other repos which need to be merged with this?

n/a

#### Addresses Issue(s):

JW8-1256
GitHub - #2696

### CODE REVIEW

**Comment by johnBartos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  🛠 There are modified src files, but no test changes. Add tests if you're able to.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  🗿 Set a milestone. It should be the ticket's fix version in JIRA.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by waxidiotic** [comment]
Awaiting on a fix version from Alicia in JIRA, then I'll add it here. Also don't think a test is needed but let me know otherwise.

**Comment by waxidiotic** [comment]
@dannyfinks confirmed the one automated failure is a known issue that @msiddique is fixing.

**Comment by johnBartos** [comment]
@waxidiotic You can add a unit test to this suite: https://github.com/jwplayer/jwplayer/blob/master/test/unit/browser-version-test.js

The test(s) can verify that that we're not returning UC as chrome.

**Pull request merged**
