### PR TITLE
Added custom property for the injected stylesheet

### PR DESCRIPTION
**Pull request by nithin-raj**
Added id as "jwplayer-styles" to injected style sheet which will provide the user on identifying the injected style easily.

### CODE REVIEW

**Comment by robwalch** [comment]
The player can add more than one stylesheet to the page so this won't do. We'd want unique ids, but maybe add a custom attribute so that you could query all jw stylesheets in the DOM.

**Comment by nithin-raj** [comment]
Agreed, added a custom attribute and removed the id property.

**Comment by robwalch** [comment]
These changes will be superseded by the simple-style-loader. @johnBartos is working on consolidating utils.css with the style loader used to add jwplayer's view css. I like the idea of an attribute that 'stamps' the element as a jw element. This could be useful for us as well when embedding multiple players so that we can avoid injecting identical css for multiple players.

**Comment by robwalch** [comment]
See #1201 and https://github.com/jwplayer/simple-style-loader/blob/master/addStyles.js#L87

Each style tag will have a 'data-jwplayer-id' attribute. The first will be a global styles element used by all players. The value for the attribute on that element will simply be the webpack module id of the loader module. Players that define their own styles will create a new element who's 'data-jwplayer-id' attribute value is set to the player id.

**Comment by johnBartos** [comment]
I'm going to close this since the the new version (0.3.0) of simple-style-loader fixes this issue https://github.com/jwplayer/simple-style-loader. We use simple-style-loader to apply styles to the player. This feature will be available in 7.5.0 and the data tag looks like `data-jwplayer-id=...`

**Pull request closed without merging**
