### PR TITLE
Improve timeslider UI and controlbar background

### LINKED ISSUE #2189: Use strict-math in Less
Strict Math is an option in Less that requires math expressions to be wrapped in parentheses. This will allow us to remove some weird workarounds for `calc` and shorthand properties.

### PR DESCRIPTION
**Pull request by radium-v**
### This PR will...
Make the controlbar and timeslider look all cool and stuff

### Are there any points in the code the reviewer needs to double check?
* Addresses Strict Math (Fixes #2189) See http://lesscss.org/usage/#command-line-usage-strict-math
* These visual adjustments differ from the design spec documents and have been approved by the Design Team:
  * The time/thumbnail/cue tooltip arrow has been flipped to be more like a traditional tooltip.
  * The controls background gradient has been extended and softened to blend better on bright.
* Animations/transitions on the timeslider may not be relevant on devices without a dedicated hover state.

#### Addresses Issue(s):
JW8-95
JW8-283

### CODE REVIEW

**Comment by robwalch** [comment]
If you write "Fixes #2189" in the description, merging this PR will close that ticket.

**Comment by karimJWP** [comment]
test this please

**Comment by egreaves** [comment]
test this please

**Comment by egreaves** [comment]
Noticed a few things:

- Buffer icon needs improvement
- Active state isn't being set for the settings menu (@johnBartos to ensure class is added in https://github.com/jwplayer/jwplayer/pull/2250)
- Live duration text needs to be evenly spaced (addressed in https://github.com/jwplayer/jwplayer/pull/2234)

**Pull request merged**
