### PR TITLE
[JW8-11903] Remove duplicate listener group "focus" for initFocusListeners

### PR DESCRIPTION
**Pull request by zetagame**
### This PR will...
Implement separate listener group for initFocusListeners

### Why is this Pull Request needed?
Prevent naming collisions with 'focus' which was already a separate listener group.

#### Addresses Issue(s):

JW8-11903

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Review by robwalch — APPROVED** [review]

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1856/) MULTI Build for commit 30e4f287bb0e27a7463865abdf56a585474e56a5 did not complete (FAILURE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9271/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9271/consoleFull) jwplayer build FAILURE
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/consoleFull) jwplayer unit tests NOT_STARTED
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by esaari** [comment]
test this please

**Comment by jwrobot-player** [comment]
[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1857/) MULTI Build for commit 30e4f287bb0e27a7463865abdf56a585474e56a5 did not complete (${PHASE_RESULT}).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/none/consoleFull) jwplayer build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/none/consoleFull) jwplayer unit tests NOT_STARTED
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/none/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Review by robwalch — APPROVED** [review]

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1858/) MULTI Build for commit 909a55d5d37e30baf600c1b8594e07358b88493b is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9273/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9273/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6225/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6225/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28281/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28281/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23745/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23745/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5918/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28281/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28281/archive/test/view/) Views

**Pull request merged**
