### PR TITLE
Best practice changes

### PR DESCRIPTION
**Pull request by zetagame**
### This PR will...
Remove redundant UI events.

### Why is this Pull Request needed?
Lots of things we listen to dispatch clicks (as intended by browser to help bring parity between the experience of using a mouse or not using a mouse). Instead of listen to lots of things that dispatch clicks after, let's just listen to the clicks!

#### Addresses Issue(s):

JW8-###

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by jwrobot-player** [comment]
[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1869/) MULTI Build for commit a75c3869a11c67a22b35e0ec5152e66ad0ddccbc is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9285/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/9285/consoleFull) jwplayer build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6236/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/6236/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28285/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/28285/consoleFull) jwplayer-commercial build SUCCESS
[:clipboard:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/23749/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/23749/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber: Cucumber Integration Tests](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/5921/allure/) UNSTABLE
[:jack_o_lantern:](http://player-pr-test-jenkins.longtailvideo.com/builds/28285/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/28285/archive/test/view/) Views

**Review by robwalch — COMMENTED** [review]
An explanation of why this is a followup rather than part of the recent click refactor (#3862 #3874 #3875) would be useful. We are releasing those changes after a lot of testing so recognizing and addressing this tech-debt now is troubling.

**Comment by zetagame** [comment]
> An explanation of why this is a followup rather than part of the recent click refactor (#3862 #3874 #3875) would be useful. We are releasing those changes after a lot of testing so recognizing and addressing this tech-debt now is troubling.

The tickets that necessitated the addition of a click handler (VoiceOver & floating player close clickthrough) didn't necessitate this level of change. This PR was posted at the same time as the original, but would greatly increase the scope of testing, which didn't seem appropriate for a patch release given the cadence of our release cycle.

**Comment by robwalch** [comment]
The scope of testing was pretty high already and will need to be repeated, so I think you missed the mark in terms of saving us cycles in the long term.

**Review by robwalch — COMMENTED** [review]
Makes sense. Add TE members as reviewers. The blocker for these changes is less about code review (you own this now) and more about test resources and release planning.

**Pull request closed without merging**
