### PR TITLE
Add Polish translation

### PR DESCRIPTION
**Pull request by mtoczko**
### This PR will...
Add pl translation (pl.json)

### Why is this Pull Request needed?
Adds a Polish translation to the player

### Are there any points in the code the reviewer needs to double check?
No

### Are there any Pull Requests open in other repos which need to be merged with this?
No

#### Addresses Issue(s):

JW8-###

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by aliciahurst** [comment]
Hi @mtoczko, thank you for your submission. This isn't documented, but we require translation submissions to originate in CSV format rather than JSON. We'll work on adding a template for that going forward. In the meantime, I've already converted your submission via copy and paste. We will review your translations internally and include Polish support in an upcoming release. Thank you!

**Comment by mtoczko** [comment]
Hi @aliciahurst, 
When will the Polish language be added?

**Comment by aliciahurst** [comment]
Hi @mtoczko I'm so sorry for the delay! We'll target 8.16.0 due out in Q3!

**Comment by mtoczko** [comment]
Hi, @aliciahurst 
There are news on this topic? :)

**Pull request closed without merging**
