### PR TITLE
Add missing “interaction” play reason metadata

### PR DESCRIPTION
**Pull request by robwalch**
I found many calls in the view that would result in a play with no play reason data. This is not the reason for all unknown plays, but should improve reporting on "interaction" plays.

JW7-3344

### CODE REVIEW

**Comment by robwalch** [comment]
@pajong make sure you test this. I just added code where I saw it was missing or needed improvement.

@dannyfinks this shows there are a few gaps in the interaction play reason testing. If the controlbar is shown, or the seek is called with keyboard, this will kick off playback.

**Comment by dannyfinks** [comment]
Thanks for digging in. I'll update the tests to include these interactions.

**Comment by robwalch** [comment]
test this please

**Comment by pajong** [comment]
test this please

**Comment by dannyfinks** [comment]
@robwalch when I focus on the player and start playback via keyboard shortcut's 1-9 when the player is idle the play reason is returned as UI Interaction. Perhaps it should be 4?

**Pull request merged**
