### PR TITLE
Remove Small UI (Compact Mode)

### PR DESCRIPTION
**Pull request by hghazzi**
Removed all reference to small UI/compact mode, as well as the drawer
in the control bar.

JW7-2465

### CODE REVIEW

**Comment by pajong** [comment]
@arup87 @dannyfinks Do you mind testing this before merging, so that nothing disastrous happens when we merge this? Thank you!

**Comment by johnBartos** [comment]
`ERROR: Build step failed with exception
java.lang.IllegalArgumentException: Illegal choice for parameter CUCUMBER_PROFILE: `

**Comment by hghazzi** [comment]
test this please

**Comment by dannyfinks** [comment]
test this please

**Comment by robwalch** [comment]
test this please

**Pull request merged**
