### PR TITLE
Support new google cast button

### PR DESCRIPTION
**Pull request by shashu10**
### This PR will...
Support the new google cast button
https://developers.google.com/cast/docs/chrome_sender_integrate#cast_button

### Why is this Pull Request needed?
The old cast button uses the v0 custom components API which will be deprecated. This change is forward compatible with the new v1 custom component API and is officially supported by the Cast SDK.

### Are there any points in the code the reviewer needs to double check?
This is simple change that renames the old cast button.google-cast-button to the new google-cast-launcher syntax. Please check if there are other instances where this needs to be renamed.

### Are there any Pull Requests open in other repos which need to be merged with this?
no

#### Addresses Issue(s):
Users not being able to use React JS which automatically uses new v1 custom component syntax. crbug.com/843421

JW8-1815

### CODE REVIEW

**Comment by robwalch** [comment]
Hi @shashu10,

It looks like the travis build requires our API token to perform checks with danger.js. @johnBartos maybe we could make that fail gracefully for forked PRs?

Thanks for the changes! At first glance it looks pretty thorough. We'll have to get the build working here or on our end (merge into a feature or bugfix branch) to give it a spin.

**Comment by shashu10** [comment]
Bump. This is a very simple change with mostly renaming of variables. Let me know if I can help in any way.

**Comment by shashu10** [comment]
Just wanted to get a status and ETA. The next release sounds good. Thanks

**Comment by shashu10** [comment]
Ping. Any status update?

**Comment by robwalch** [comment]
Hi @shashu10,
The plan is to release v8.6.0-beta.1 in the two weeks. These changes will be included. 8.6.0 will follow mid October.

**Pull request merged**
