### PR TITLE
JW8 - add title secondary in player and info overlay

### PR DESCRIPTION
**Pull request by quebello**
### This PR will ...
modify the code to add a secondary title (subtitle) of a media in the player and in the content of the info overlay

### Why is this Pull Request needed?
For our project, we need to display a subtitle (secondary title) in the player and in the info overlay.
For example, show the episode title under the serie title.

### Are there any points in the code the reviewer needs to double check?
no

### Are there any Pull Requests open in other repos which need to be merged with this?
no

#### Addresses Issue(s):

JW8-3285 https://github.com/jwplayer/jwplayer/issues/3285

### CODE REVIEW

**Comment by karimMourra** [comment]
@quebello why not use `jw-title-secondary`?

**Comment by johnBartos** [comment]
Hi @quebello, thanks for the PR. However, we won't be merging this because you can do it with our existing API. The `description` and `title` fields accept HTML input. For example:

```
jwplayer().setup({
    decription: '<h2>Hello!</h2>
});
```

Unfortunately I just found a bug with this feature - the HTML is added, but the text is stripped out. The last working version is 8.7.3. We'll put in a bug ticket and fix it in the near future. Thanks for helping us find this!

**Comment by quebello** [comment]
Hello, in our case the description is a short description about de media.

**Comment by johnBartos** [comment]
@quebello Are the existing title & description config options not sufficient for your usecase?

**Comment by quebello** [comment]
@johnBartos unfornunately not, our business is showed/shared a lot of media contents and we have the possibility to share our embed with jwplayer and this feature meets our needs and maybe for other people ^^. I dont know if you understand ?

**Comment by johnBartos** [comment]
@quebello Before you pass it to JW just put the secondary title into HTML, and pass that in. It sounds like you know what the title is (because you would have passed it into the new config option), so I'm not sure I understand why this is a blocker

**Comment by quebello** [comment]
@johnBartos the first problem if i put some html in the title or description field, the html is hardcoded in the overlay info. Its so ugly ^^, i think. This is why i suggest a pretty solution :)

**Pull request closed without merging**
