### PR TITLE
Display replay icon in control-bar in complete state

### PR DESCRIPTION
**Pull request by dannyfinks**
### Changes proposed in this pull request:

*- In complete state, display the replay icon in the control-bar, not the play icon*

### CODE REVIEW

**Comment by dannyfinks** [comment]
@egreaves @madikarizma would like to have more consistency by adding the replay icon in the control-bar in complete state, however the font-size of the replay icon in the control-bar is too small. This also seems like an issue in the display, regarding the size of the replay icon compared to the rewind icon. If this doesn't make sense we can close this out, but if we can work on making the icons consistent and correct size would provide a better UX.

**Comment by egreaves** [comment]
@dannyfinks I see what you're saying and I agree. We can increase the size of the rewind button to be consistent with the others. I or @madikarizma can push that change then accept this PR.

**Comment by madikarizma** [comment]
@dannyfinks @egreaves 👍

**Comment by dannyfinks** [comment]
Replay icon in current state:
image

**Comment by robwalch** [comment]
This looks good and very simple to me. @jw-kaurand @madikarizma @egreaves why did you guys not comment or merge @dannyfinks fix?

**Comment by robwalch** [comment]
test this please

**Pull request merged**
