### PR TITLE
Add back the Occitan translations

### PR DESCRIPTION
**Pull request by karimMourra**
### This PR will...
Add back the Occitan translation that was removed in #3357
### Why is this Pull Request needed?
@Quenty31's contribution of Occitan translations #3353 was accidentally merged to master and therefore had to be reverted. This PR reverts the revert, to add the translation.
### Are there any points in the code the reviewer needs to double check?
n/a
### Are there any Pull Requests open in other repos which need to be merged with this?
n/a
#### Addresses Issue(s):
n/a

### CODE REVIEW

**Comment by johnBartos** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true">Warnings</th>
    </tr>
  </thead>
  <tbody><tr>
      <td>:warning:</td>
      <td>

  🛠 There are modified src files, but no test changes. Add tests if you're able to.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  🔎 Assign some reviewers or assignees.
  </td>
    </tr>
  
<tr>
      <td>:warning:</td>
      <td>

  🗿 Set a milestone. It should be the ticket's fix version in JIRA.
  </td>
    </tr>
  </tbody>
</table>



<p align="right">
  Generated by :no_entry_sign: <a href="http://github.com/danger/danger-js/">dangerJS</a>
</p>

**Comment by Quenty31** [comment]
Thanks :)

**Comment by karimMourra** [comment]
note to reviewer: failed integration tests are unrelated to these changes. they are failed ad tests for bidding events

**Comment by karimMourra** [comment]
Lord @pajong , unit tests were added in https://github.com/jwplayer/jwplayer/pull/3360. I will run the tests again before merging, but should be good to merge

**Pull request merged**
