### PR TITLE
[JW8-11308] Add new API to expose player viewable percentage

### PR DESCRIPTION
**Pull request by pajong**
### This PR will...
- Add new API to expose `visibility`, which represents the percent viewable of the player

### Why is this Pull Request needed?
- Feature request from the Data Team

#### Addresses Issue(s):

JW8-11308

### Checklist
- [ ] Jenkins builds and unit tests are passing
- [ ] I have reviewed the automated results

### CODE REVIEW

**Comment by robwalch** [comment]
cc @paulmandal @s-seibert @henryhlee - We discussed a method to get percentage viewable. We're adding it here in 8.18, it's called `getPercentViewable()`:

```
 /**
         * Gets the player's visibility.
         * @returns {Number} Returns a number between 0 and 1 that represents how much of the player is in the document viewport.
         * Returns 0 if the player is not in an active tab, or if the player is completely out of the viewport.
         * @since v8.18.0
         */
        getPercentViewable() {
            return core.get('visibility');
        },
```

**Review by robwalch — APPROVED** [review]

**Review by nebnitt — APPROVED** [review]
very cool 👍

**Review by nebnitt — CHANGES_REQUESTED** [review]
Hmm - seems some tests may need updating here as the build is failing

**Review by nebnitt — APPROVED** [review]
lgtm now that tests pass!

**Review by zetagame — APPROVED** [review]

**Review by mamaddox — APPROVED** [review]

**Comment by jwrobot-player** [comment]
NEW JENKINS

[:exclamation:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/12/) MULTI Build for commit c36fc53bedb23e76dd7ea8118159c5c107e64330 did not complete (${PHASE_RESULT}).
[:building_construction:](https://jenkins.jwplayer.com/view/JW7/job/jw7-opensource/none/)[:black_small_square:](https://jenkins.jwplayer.com/view/JW7/job/jw7-opensource/none/consoleFull) jwplayer build NOT_STARTED
[:building_construction:](https://jenkins.jwplayer.com/view/JW7/job/jw7-opensource-unit-tests/none/)[:black_small_square:](https://jenkins.jwplayer.com/view/JW7/job/jw7-opensource-unit-tests/none/consoleFull) jwplayer unit tests NOT_STARTED
[:building_construction:](https://jenkins.jwplayer.com/view/JW7/job/jw7-commercial/none/)[:black_small_square:](https://jenkins.jwplayer.com/view/JW7/job/jw7-commercial/none/consoleFull) jwplayer-commercial build NOT_STARTED
[:building_construction:](https://jenkins.jwplayer.com/view/JW7/job/jw7-commercial-unit-tests/none/)[:black_small_square:](https://jenkins.jwplayer.com/view/JW7/job/jw7-commercial-unit-tests/none/consoleFull) jwplayer-commercial unit tests NOT_STARTED
[:cucumber:.js Allure Report](https://jenkins.jwplayer.com/view/JW7/job/jw7-commercial-cucumber-wdio/none/allure/) NOT_STARTED
[:eggplant:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/none/archive/test/view/) Views

**Comment by cesarrecio-enroute** [comment]
test this please

**Comment by jwrobot-player** [comment]
NEW JENKINS

[:warning:](https://jenkins-player.longtailvideo.com/job/jw7-pr-multi-opensource/1583/) MULTI Build for commit c36fc53bedb23e76dd7ea8118159c5c107e64330 is unstable (UNSTABLE).
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8895/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource/8895/consoleFull) jwplayer build SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5950/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-opensource-unit-tests/5950/consoleFull) jwplayer unit tests SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26897/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/26897/consoleFull) jwplayer-commercial build SUCCESS
[:building_construction:](https://jenkins-player.longtailvideo.com/job/jw7-commercial/22564/)[:black_small_square:](https://jenkins-player.longtailvideo.com/job/jw7-commercial-unit-tests/22564/consoleFull) jwplayer-commercial unit tests SUCCESS
[:cucumber:.js Allure Report](https://jenkins-player.longtailvideo.com/job/jw7-commercial-cucumber-wdio/4826/allure/) UNSTABLE
[:eggplant:](http://player-pr-test-jenkins.longtailvideo.com/builds/26897/archive/test/squash/) Manual Tests
[:tv:](http://player-pr-test-jenkins.longtailvideo.com/builds/26897/archive/test/view/) Views

**Review by karimMourra — APPROVED** [review]

**Pull request merged**
