### PR TITLE
increase scale of position number

### PR DESCRIPTION
**Pull request by maxstoller**
#1325 

Thanks!

### CODE REVIEW

**Comment by johnBartos** [comment]
How about we just remove the rounding altogether? That's what we do in our HTML5 implementation

**Comment by maxstoller** [comment]
Even better! Thanks @johnBartos. Is this going to make it to the commercial release? If not, does that mean we have to build it ourselves?

**Comment by johnBartos** [comment]
Yeah it will make it in to 7.5, thanks for your contribution! I'll test this out and merge it in soon

**Comment by maxstoller** [comment]
Great, thanks!

**Comment by robwalch** [comment]
Check RTMP / API for impact on time and complete events.

**Pull request merged**
